### ISSUE TITLE
Proposal: add short name 

### ISSUE THREAD

**Issue by rhaist** [MISP/misp-warninglists#142]
Both `description` and `name` are long form text fields.
A am currently integrating the misp-warningslist into OpenCTI and it would be nice to have an additional short name for each warninglists that can be used as tag in a front end. e.g.:

```
{
  "description": "Event contains one or more entries part of the RFC 1918 CIDR blocks",
  "list": [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip"
  ],
  "name": "List of RFC 1918 CIDR blocks",
  "short": "RFC1918",
  "type": "cidr",
  "version": 3
}
```

Another possibility would be to use the `name` field for the short version as there already is a redundant long form explanation with `description`.

I would be willing to prepare a PR for all existing lists if you are fine with any of those solutions. Just let me know.

**Comment by iglocska** [comment]
Those changes are definitely not in scope considering the expected stability of the format, we generally don't want to modify the conventions due to mismatched capabilities/conventions of tools / other standards. Misp is just one of many tools relying on the warning lists.

I think the best recommendation for a short name like that is to have a mapping table on the other end. Hope this helps.

**Comment by rhaist** [comment]
I understand. But to which field do I map? The lists don't have a stable ID and the name and description fields could be updated e.g. for wording or spelling errors.

**Comment by iglocska** [comment]
Generally the name is stable. We consider it to be the key - if it gets updated we have the same issue as a short name with a typo / updated name.

**Comment by iglocska** [comment]
Perhaps one thing we could do at one point to be more inline with some of our other structures is to start having uuids assigned to the lists. We can raise that internally in the MISP project team.
