### ISSUE TITLE
generator.py:download_to_file fails when file not present

### ISSUE THREAD

**Issue by sustefil** [MISP/misp-warninglists#156]
I ran the `generate-publicdns.py` generator and on line:

https://github.com/MISP/misp-warninglists/blob/main/tools/generator.py#L20

It failed with FileNotFoundError.

Fix is easy, I will create a pull request :) 

Btw thanks @digihash for refactoring the generators!

**Comment by digihash** [comment]
Thanks for the fix @sustefil
