### ISSUE TITLE
blacklisted Domain list

### ISSUE THREAD

**Issue by vaibhavpandey86** [MISP/misp-warninglists#175]
Hello All,

I just do have one question.
I need to find the blacklisted Domain name(not IP) list in MISP feed, how to get that, how to search?
Likewise how do we usually search.

Thanks,
Vaibhav

**Comment by adulau** [comment]
It depends of your MISP configuration. The warning-lists are available in each MISP instance and you can enable the warning-lists that you would like.

**Comment by vaibhavpandey86** [comment]
Actually I want to download the list.
could you please help finding exact feed and how to download.
All I am getting event related to feed which contains some blacklist domain.
