### ISSUE TITLE
Secondary Google DNS Server not on Warning list.

### ISSUE THREAD

**Issue by spitzbuaamy** [MISP/misp-warninglists#208]
Please add 8.8.4.4 to the Warninglist of public DNS Servers.

**Comment by adulau** [comment]
Not sure which warning-list you are using but 8.8.4.4 is included:

https://github.com/MISP/misp-warninglists/blob/main/lists/public-dns-v4/list.json#L5260

**Comment by spitzbuaamy** [comment]
Ah, in this case there must be an issue with my MISP warninglist instance. I don't have this IP on this warning list. 
Thank you for the quick answer.
