### ISSUE TITLE
Stackpath CDN Warning List appears to be broken (empty)

### ISSUE THREAD

**Issue by jberkers42** [MISP/misp-warninglists#215]
Hi team,

I noticed that list ID 61 in Warninglist feature is empty, and navigated to the referenced URL in the description.  This corresponds to the file in this repo at:

`misp-warninglists/lists/stackpath/list.json`

Scrolling through the history, I noticed that there was at least one prior comment to say "Fixed stackpath".

Any chance of populating this list once again?

Many thanks.

JohnB

**Comment by jberkers42** [comment]
Did some digging this morning.  Looks like the url for the IPBlocks File changed:

[StackPath IP Blocks](https://k3t9x2h3.map2.ssl.hwcdn.net/ipblocks.txt)

**Comment by adulau** [comment]
Thank you very much for the contribution, the list has been updated https://github.com/MISP/misp-warninglists/commit/7a6eebe47b540685f8dac2f991887a7839242dcd
