### ISSUE TITLE
New List: Tenable Cloud Scanners/Sensors

### ISSUE THREAD

**Issue by jberkers42** [MISP/misp-warninglists#225]
Tenable.io customers often scan their Internet-facing infrastructure using Tenable.io Cloud Scanners or Sensors. Given that this frequently results in detections of various types, I would like to suggest/request the addition of a warninglist for Tenable Cloud Sensors.

Tenable document the details here: [Tenable Cloud Sensors](https://docs.tenable.com/tenableio/Content/Platform/Settings/Sensors/CloudSensors.htm)

A json extract of the data is available here: [data.json](https://docs.tenable.com/ip-ranges/data.json)

I am willing to attempt writing the script to scrape/parse/output, but am less experienced with Python than other languages, so feedback would be essential.

**Comment by adulau** [comment]
Thanks for the PR.
