### ISSUE TITLE
Potential domains to be included in whats-my-ip warning list

### ISSUE THREAD

**Issue by zoni171** [MISP/misp-warninglists#23]
2ip.ru
2ip.tools
aboutmyip.com
api.wipmania.com
bearsmyip.com
check-my-ip.net
checkip.dns.he.net
checkip.dyndns.es
checkip.dyndns.info
checkip.dyndns.org
checkip.narak.com
checkmyip.com
cmyip.com
cmyip.net
crymyip.com
curlmyip.com
curlmyip.net
dawhois.com
dnswatch.info
dpool.sina.com.cn
findmyip.org
findmyipaddress.com
formyip.com
freegeoip.net
geoip.co.uk
geoip.vmn.net
geoiptool.com
get-myip.com
getmyip.co.uk
getmyip.org
ifconfig.me
inet-ip.info
ip-1.com
ip-addr.es
ip-address.cc
ip-address.ru
ip-adress.com
ip-api.com
ip-check.info
ip-detect.net
ip-info.org
ip-info.xyz
ip-ping.ru
ip-who-is.com
ip-whois.net
ip.amulex.com
ip.cctv.pk
ip.chinaz.com
ip.cn
ip.my-proxy.com
ip.taobao.com
ip.telize.com
ip.tool.la
ip.tyk.nu
ip.webmasterhome.cn
ip138.com
ip2location.com
ip2nation.com
ipaddress.com
ipaddress.org
ipaddresscheck.com
ipchecker.info
ipify.org
ipinfo.io
ipinfodb.com
ipleak.net
iplocation.net
iplogger.ru
ipmonkey.com
iptrackeronline.com
j.maxmind.com
l2.io
meip.eu
meuip.net.br
mon-ip.com
mycamip.com
myglobalip.com
myip.am
myip.by
myip.cc
myip.cf
myip.ch
myip.cn
myip.co.il
myip.co.nz
myip.com.br
myip.com.tw
myip.com.ua
myip.cz
myip.dk
myip.dnsdynamic.org
myip.dnsomatic.com
myip.dramor.net
myip.easylife.tw
myip.es
myip.eu
myip.fi
myip.gr
myip.gratis
myip.heltech.se
myip.ht
myip.info
myip.io
myip.is
myip.israel.net
myip.jacware.com
myip.knet.ca
myip.kz
myip.ma
myip.ms
myip.mudfish.net
myip.mx
myip.mysau.com.au
myip.net
myip.nl
myip.nmonitoring.com
myip.northstate.net
myip.nu
myip.opendns.com
myip.ozymo.com
myip.report
myip.rs.sr
myip.ru
myip.sdu.dk
myip.se
myip.shorty.org
myip.si
myip.surfeasy.com
myip.telespex.com
myip.tk
myip.tw
myip.ua.edu
myip.uconn.edu
myip.v6shell.org
myip.zone
myipinfo.net
myipnow.com
myiponline.com
mylocation.org
qualmeuip.com.br
readip.info
shmyip.com
show-ip.com
show-my-ip.de
showip.net
showipinfo.net
showmemyip.com
showmyip.co.uk
showmyip.com
showmyip.com.ar
showmyip.gr
showmyipaddress.com
showmyipaddress.eu
showmyipnow.com
smart-ip.net
tell-my-ip.com
tracemyip.com
tracemyip.org
trackip.net
ultratools.com
utrace.de
vinflag.com
w.hatsmyip.com
whatismyip.akamai.com
whatismyip.ca
whatismyip.everdot.org
whatmyip.us
whats-my-ip-address.org
whatsmyip.us
whatsmyipaddress.com
whatsmyipaddress.net
whereisip.net
whoer.me
whoer.net
www.ip[.]cn
yougetsignal.com
youip.net
your-ip-address.com
your-ip-fast.com
yourip.us

**Comment by Maijin** [comment]
You can make a pull-request you can even use the github web-editor to add those without needing to manipulate git. https://help.github.com/articles/editing-files-in-your-repository/
