### ISSUE TITLE
Add URL shorteners

### ISSUE THREAD

**Issue by cert-lexsi** [MISP/misp-warninglists#26]
Diff with https://phishing-initiative.lu list of active URL shortener to complete MISP warninglist:

1url.com
4sq.com
7.ly
adf.ly
adflav.com
adfoc.us
admy.link
al.ly
amzn.to
any.gs
ay.gy
bc.vc
bit.do
bit.ly
bitly.com
biturl.io
buzurl.com
clockurl.com
cur.lv
curl.lv
cut.by
cutt.us
db.tt
doiop.com
dyo.gs
easyurl.net
fas.li
fave.co
filesonthe.net
filoops.info
flic.kr
frama.link
fur.ly
gentleurl.net
git.io
golinks.ncsu.edu
goneviral.com
goo.cl
goo.gl
hda.me
hec.su
hit.my
hotshorturl.com
hyperurl.co
is.gd
ity.im
j.mp
keeplinks.me
kleinurl.de
lc.cx
lemde.fr
libr.ae
link.zip.net
linkpaid.net
lnkd.in
lnked.in
lnx.lu
lok.biz
lynk.my
mcaf.ee
megaline.co
miniurls.co
minu.me
normalurl.com
notlong.com
nubr.co
one-link.de
ouo.io
ouo.press
ow.ly
oxu.be
ph.dog
po.st
prettylinkpro.com
q.gs
qqc.co
qr.ae
qr.net
redd.it
s.id
safelinking.net
scrnch.me
sdu.sk
sh.st
shadyurl.com
shink.in
shorl.com
short.st
shorte.st
shorturl.com
shrinkee.com
shrinkurl.in
smarturl.it
snip.ly
sptfy.com
su.pr
t.cn
t.co
tcrn.ch
thinfi.com
tighturl.com
tiny.cc
tinyarrows.com
tinylinks.co
tinyurl.com
tldrify.com
tmblr.co
tny.im
tr.im
tubeviral.com
tweez.me
twitthis.com
u.bb
u.to
ultrafiles.net
urlbeat.net
urlpetite.fr
urlz.fr
v.gd
viralurl.biz
viralurl.com
virl.ws
vur.me
vurl.bz
vurl.com
vzturl.com
wp.me
x.co
xlinkz.info
xn--hgi.ws
xtu.me
y2u.be
yourls.org
youtu.be
yyv.co
zi.ma
zzb.bz

**Comment by cert-lexsi** [comment]
+
http://urls.fr

**Comment by adulau** [comment]
Could you do a PR? Thank you.

**Comment by cert-lexsi** [comment]
done but i forgot to add the latest one = urls.fr :-(

**Comment by Rafiot** [comment]
A PR has been made, closing.
