### ISSUE TITLE
Erroneous Entry in "List of known public DNS resolvers expressed as hostname"

### ISSUE THREAD

**Issue by cgrangerdc** [MISP/misp-warninglists#275]
This list appears to have a typo: 

https://github.com/MISP/misp-warninglists/blob/fc9f8542e9e6a9a4c11bb0b94d2a7d326761929c/lists/public-dns-hostname/list.json#L9394

This issue causes any indicator containing the string "77" to match on this warning list.

**Comment by adulau** [comment]
Thanks for the report. It was useful as I discovered one of a generating script was not properly filtering out illegal domain. It should be fixed. If you see something else, don't hesitate.
