### ISSUE TITLE
Add MOZ500 Top500

### ISSUE THREAD

**Issue by cgi1** [MISP/misp-warninglists#29]
Could be a good list: https://moz.com/top500/pages

**Comment by cgi1** [comment]
Due to the new [price model](http://www.alexa.com/plans?utm_expid=142284645-2.NGfQiMJFQoWbvYbw0lAlwA.0&utm_referrer=http%3A%2F%2Fwww.alexa.com%2Ftopsites)

**Comment by SteveClement** [comment]
Added: https://github.com/MISP/misp-warninglists/commit/284b5fa2c8c032780bd0e42fb55a3e307c1cb58e
