### ISSUE TITLE
TOR node list

### ISSUE THREAD

**Issue by morallo** [MISP/misp-warninglists#33]
It would be interesting to be able to identify Tor nodes in IP address attributes. They may not be necessarily false positives, but their relevance as an IOC is very relative.

Cons: as this is a dynamic list, it would need to be updated regularly, and preferably in an automatic way.

Is there any automated way to keep warning lists up to date?

**Comment by adulau** [comment]
The easiest and the fastest way would be to use the MISP feed (especially with the new functionality 2.4.73). Here is the JSON of a Tor exit node:

~~~~
{
    "Feed": {
        "id": "8",
        "name": "Tor exit nodes",
        "provider": "TOR Node List from dan.me.uk",
        "url": "https:\/\/www.dan.me.uk\/torlist\/?exit",
        "rules": "{\"tags\":{\"OR\":[],\"NOT\":[]},\"orgs\":{\"OR\":[],\"NOT\":[]}}",
        "enabled": true,
        "distribution": "0",
        "sharing_group_id": "0",
        "tag_id": "615",
        "default": false,
        "source_format": "csv",
        "fixed_event": true,
        "delta_merge": true,
        "publish": false,
        "override_ids": false,
        "settings": "{\"csv\":{\"value\":\"\",\"delimiter\":\"\"},\"common\":{\"excluderegex\":\"\"}}",
        "input_source": "network",
        "delete_local_file": false,
        "lookup_visible": true
    },
    "Tag": {
        "id": "615",
        "name": "osint:source-type=\"block-or-filter-list\"",
        "colour": "#004f89",
        "exportable": true,
        "org_id": "0",
        "hide_tag": false
    }
}

~~~~

**Comment by morallo** [comment]
Thx for the reply @adulau 

I had already considered this option after seen [this issue](https://github.com/MISP/MISP/issues/1999), 

However, I was not aware of the new feed features in 2.4.73, and previous versions wouldn't cover my desired use case.

**Comment by adulau** [comment]
You're welcome. Let us know if 2.4.73 helps there.

**Comment by adulau** [comment]
I'll close the issue as this is solved with the feed feature. If this is not the case, feel free to reopen. Thank you.
