### ISSUE TITLE
To add: URLs/Domains of automated malware analysis tools

### ISSUE THREAD

**Issue by h122015** [MISP/misp-warninglists#45]
For example: 

hybrid-analysis.com
virustotal.com
...

**Comment by adulau** [comment]
Good idea. I think we will have a day session to create all the new warning-lists.

**Comment by adulau** [comment]
First version of the ones I know about https://github.com/MISP/misp-warninglists/commit/8ec2a3a98d19ca25a3ab3b906b23d10577c06889 if you know other, feel free to let us know.
