### ISSUE TITLE
Windows 10 connection endpoints

### ISSUE THREAD

**Issue by StefanKelm** [MISP/misp-warninglists#77]
Would it make sense to have these three lists as a new warning list as well?

https://docs.microsoft.com/en-us/windows/privacy/manage-windows-endpoints
https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1709-non-enterprise-editions
https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1803-non-enterprise-editions

If yes, a new warning list (will contain duplicates to existing lists) or integrate into others (contains Akamai, though)?

**Comment by adulau** [comment]
Nice catch! This would make sense.
